[[docs]]
Home = "index.md"

[[docs.About]]
Project = "description.md"
Built_With = "built-with.md"

[[docs.Installation]]
Prerequisites = "prerequisites.md"
Setup = "setup.md"

[[docs.Usage]]
Overview = "overview.md"
Getting_Started = "getting-started.md"
Advanced = "advanced.md"
Workflows = "workflows.md"

[[docs]]
Structure = "structure.md"

[[docs]]
Tasks = "tasks.md"

[[docs]]
License = "license.md"

[[docs.Contact]]
Team = "team.md"
Support = "support.md"
Social_Media = "social-media.md"

[[docs]]
Acknowledgments = "acknowledgments.md"

[[docs.API]]
Authentication = "authentication.md"

[[docs.API.Endpoints]]
Users = "users.md"
Products = "products.md"
Orders = "orders.md"

[[docs.API]]
Error_Codes = "api/errors.md"

[[docs.Developer]]
Contributing = "contributing.md"
Architecture = "architecture.md"

[[docs]]
FAQ = "faq.md"

[[docs]]
Changelog = "changelog.md"

[readme.meta]
title = "ClearDocs"
subtitle = "OSS Documentation Assistant"
url = "example.com/montymi/ClearDocs"

[readme.about]
subtitle = """
The Open Source Software (OSS) community underpins countless businesses worldwide, with over 50% of Fortune 500 companies relying on it for their workflows—a number poised to grow as more projects gain traction. 
However, this growth hinges on consistent feature development, which is challenging without more developers. 
Research by Ravi Sen, Siddhartha S. Singh, and Sharad Borle found that adding 10 developers to a project increases average subscribers by 5.65%, demonstrating a clear link between developer engagement and user adoption.

Given this, OSS projects must prioritize lowering barriers to entry and welcoming community contributions—the very ethos of OSS. Unfortunately, this is far from the norm. 
A 2014 study revealed that only 5.4% of 2,000 projects included architectural documentation, a crucial tool for scaling and collaboration. 
While many OSS projects have achieved remarkable growth, more widespread emphasis on software architecture documentation could drive success for countless lesser-known initiatives.

Effective documentation should guide users and developers through a project’s purpose, workflow, and future direction. 
A basic overview and installation guide are insufficient; developers need clear navigation of the source code and actionable tasks, while users benefit from insight into future plans and transparent communication channels.

This README aims to set a standard for OSS documentation, improving project accessibility and fostering contributions from both the community and aspiring developers.
"""

[readme.built_with]
subtitle = """
Listing the major tools and languages used in the project helps it
appear in filtered search results for any included library.  Additionally, it
allows developers to quickly identify whether a library they are proficient
in is part of the project.  Refer to the "Markdown Links and Images" section
of the HTML version of this file to learn how these logo URLs are created.
"""

[[readme.built_with.tools]]
logo = "python"
name = "Python"
url = "https://python.org"

[[readme.built_with.tools]]
logo = "markdown"
name = "Markdown"
url = "https://daringfireball.net/projects/markdown/"

[[readme.built_with.tools]]
logo = "html5"
name = "HTML5"
url = "https://html.spec.whatwg.org/"

[readme.installation.prerequisites]
subtitle = """
Ensure you have [git](https://git-scm.com/), [python][pythonLogo-url]
(and presumably pip too). Best bet, download the official release for your platform
(Operating System) from the provided homepages and their download section. On
Windows, your best bet is to use the resulting Git Bash application that will
become available after installing git.

Comfirm prerequisites by running the following command: ```bash git --version
&& python --version && pip --version ```

Download and navigate into the repository: ```bash git clone https://github.com/montymi/ClearDocs/
&& cd ClearDocs ```

There are currently no additional prerequisites for this project.
"""

[readme.usage]
advanced = """
Advanced usage instructions should be placed here. These can include
multiple lines of detailed explanation.
"""
getting_started = """
Manually convert the section information to fit project, including
the URLs for tools, tests, and contact cards which need to be found, added,
and called.
"""
subtitle = """
Users are much more likely to use and test a project if they can quickly
determine how best to use the software and whether or not it really is what
they are looking for. Clear usage examples also give incoming developers a chance
to better understand the code and its intended use.

*Here is an example from this project that hopefully won't stand for very long:*
"""

[readme.structure]
subtitle = """
Less than 6% of GitHub projects include documentation or diagrams about
the software's architecture. Since larger projects can often have a very convoluted
source code structure, diagrams are the ideal method of displaying the flow
of the project.
